# Generated by Django 5.1.1 on 2024-09-07 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GensecCandidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrezCandidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('gensec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.genseccandidate')),
                ('prez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prezcandidate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
