# Generated by Django 5.1.1 on 2025-08-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_electionposition_remove_voter_gensec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentclub',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departmentclub',
            name='size',
            field=models.CharField(blank=True, choices=[('major', 'Major'), ('minor', 'Minor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentclub',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentclub',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
