# Generated by Django 5.1.1 on 2025-08-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_oasis_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousElectionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(db_index=True, max_length=64)),
                ('vote_signature', models.CharField(max_length=128)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_votes', to='main.electioncandidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.electionposition')),
            ],
            options={
                'indexes': [models.Index(fields=['position', 'voted_at'], name='main_anonym_positio_83b779_idx'), models.Index(fields=['candidate', 'voted_at'], name='main_anonym_candida_cbe372_idx')],
                'unique_together': {('voter_hash', 'position')},
            },
        ),
    ]
