# Generated by Django 5.1.1 on 2025-08-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_anonymouselectionvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HuelVote',
        ),
    ]
