# Generated by Django 5.1.1 on 2025-08-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_huel_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectionVote',
        ),
    ]
