# Generated by Django 5.1.1 on 2025-08-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_election_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voted_gen_sec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voted_president',
            field=models.BooleanField(default=False),
        ),
    ]
