# Generated by Django 4.2 on 2025-08-18 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_add_voting_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('voting_type', models.CharField(choices=[('su_election', 'SU Election'), ('huel_voting', 'HUEL Voting'), ('department_club', 'Department/Club Voting')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('voting_start_time', models.DateTimeField(blank=True, null=True)),
                ('voting_end_time', models.DateTimeField(blank=True, null=True)),
                ('message_before_start', models.TextField(default="Voting hasn't started yet. Please check back later.")),
                ('message_during_voting', models.TextField(default='Voting is now active! Cast your vote below.')),
                ('message_after_end', models.TextField(default='Voting has ended. Thank you for participating!')),
                ('message_inactive', models.TextField(default='Voting is currently disabled by administrators.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voting_type',)},
            },
        ),
    ]